/**
 * generate.js — assembles the single dependency-free ES module emitted for a
 * grammar: runtime + generated lexer + generated parser + generated
 * serializer + public API (parse / createPushParser / parseStream / writer).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseGrammar } from './meta.js';
import { analyzeTokens, genLexer, genStandaloneMatchers } from './lexer-gen.js';
import { ParserGen } from './parser-gen.js';
import { genSerializer } from './serializer-gen.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));

export function generateModule(grammarText, grammarFile) {
  const g = parseGrammar(grammarText, grammarFile);
  const an = analyzeTokens(g);
  const lex = genLexer(g, an);

  const gen = { constPool: new Map() };
  const pg = new ParserGen(g, an, lex, gen);
  const parserOut = pg.generate();

  const ser = genSerializer(g, an, (tokens) => genStandaloneMatchers(g, an, tokens));

  // start production drives the document loop; its body must be `X*`
  const start = g.prodByName.get(g.headers.start);
  if (!start) throw new Error(`start production ${g.headers.start} not found`);
  const startItem = start.alts[0].items.find((i) => i.kind === 'factor');
  if (!startItem || startItem.postfix !== 'star' || startItem.prim.kind !== 'call') {
    throw new Error('start production must be a star over a statement-level production');
  }
  const stmtProd = startItem.prim.name;

  // environment declarations -> parser state
  const envDecls = g.env.map((e) => {
    const t = e.type;
    if (t.startsWith('map')) return `const env_${e.name} = new Map();`;
    if (t === 'iri') return `let env_${e.name} = options.baseIRI !== undefined ? String(options.baseIRI) : ${JSON.stringify(e.init && e.init.k === 'iri' ? e.init.value : '')};`;
    return `let env_${e.name} = null;`;
  }).join('\n  ');

  const constPoolCode = [...gen.constPool.entries()]
    .map(([iri, id]) => `const ${id} = new NamedNode(${JSON.stringify(iri)});`)
    .join('\n');

  const runtime = fs.readFileSync(path.join(HERE, 'runtime.inc.js'), 'utf8');

  const code = `/* ================================================================
 * GENERATED by @rdf-shuttle/gen-js from ${path.basename(grammarFile)} — DO NOT EDIT.
 * grammar: ${g.name}  target: ${g.headers.target || '?'}  profile: ${g.headers.profile || '?'}
 * spec-ref: ${(g.headers['spec-ref'] || '').split(' — ')[0]}
 *
 * One dependency-free ES module: streaming parser (text -> RDF/JS quads),
 * push parser (chunked input, bounded memory), and serializer (quads ->
 * text) — parse and print modes of the same Shuttle relation.
 * ================================================================ */

const NTOK = ${lex.numTokens};

${runtime}

/* ---- token kinds ---- */
${lex.constsCode}

/* ---- interned curie constants (compile-time, from core-terms) ---- */
${constPoolCode}

/* ---- parser first-sets ---- */
${pg.tableDefs.join('\n')}

/* ================================================================
 * Parser factory: all machine state lives in this closure.
 * ================================================================ */
function makeParser(options, onQuad) {
  let inp = '';
  let len = 0;
  let pos = 0;
  let final = 1;
  let tk = 0;
  let ts = 0;
  let te = 0;
  let tEsc = 0;
  let tM0 = -1;
  let tMD = -1;
  let mEsc = 0;
  let m0 = -1;
  let mD = -1;
  let hitEnd = 0;
  let depth = 0;
  void tM0; void tMD; void m0; void mD;

  /* environment (grammar env block) */
  ${envDecls}

  /* fresh blank nodes: per-derivation counter (deterministic _:b0, _:b1 …) */
  let freshCtr = 0;
  function BNF() { return new BlankNode('b' + (freshCtr++)); }

  /* span-interning for named nodes */
  const iCache = new Map();
  function NN(v) {
    let t = iCache.get(v);
    if (t === undefined) { t = new NamedNode(v); iCache.set(v, t); }
    return t;
  }
  function QuadT(s, p, o) { return new Quad(s, p, o, DEFAULT_GRAPH); }

  /* pname interning: prefix -> (local -> term); short-string hashing only.
   * Invalidated when a prefix is (re)bound. */
  const pnCache = new Map();
  function expandPN(map, pfx, local) {
    let inner = pnCache.get(pfx);
    if (inner === undefined) { inner = new Map(); pnCache.set(pfx, inner); }
    let t = inner.get(local);
    if (t === undefined) { t = NN(map.get(pfx) + local); inner.set(local, t); }
    return t;
  }

  /* push-mode statement rollback support */
  let trail = null;
  function bindLabel(k, v) {
    if (trail !== null && !env_labels.has(k)) trail.push(k);
    env_labels.set(k, v);
  }

  /* quad sink: direct callback (one-shot) or per-statement buffer (push) */
  let sink = onQuad;
  const stmtBuf = [];
  function emitQ(s, p, o) { sink(new Quad(s, p, o, DEFAULT_GRAPH)); }

  function lineCol(at) {
    let line = 1;
    let last = -1;
    for (let i = 0; i < at && i < len; i++) {
      if (inp.charCodeAt(i) === 10) { line++; last = i; }
    }
    return [line, at - last];
  }
  function perr(code) {
    const [l, c] = lineCol(ts);
    throw new ShuttleSyntaxError('parse error at line ' + l + ':' + c, l, c, code);
  }
  function perrExp(kind) {
    const [l, c] = lineCol(ts);
    throw new ShuttleSyntaxError('expected ' + TOKEN_NAMES[kind] + ' but got ' + TOKEN_NAMES[tk] + ' at line ' + l + ':' + c, l, c, 'UNEXPECTED_TOKEN');
  }
  function perrAlt(kinds) {
    const [l, c] = lineCol(ts);
    throw new ShuttleSyntaxError('expected one of ' + kinds.map((k) => TOKEN_NAMES[k]).join(', ') + ' but got ' + TOKEN_NAMES[tk] + ' at line ' + l + ':' + c, l, c, 'UNEXPECTED_TOKEN');
  }
  function lexErr() {
    const [l, c] = lineCol(pos);
    throw new ShuttleSyntaxError('unrecognized token at line ' + l + ':' + c, l, c, 'LEX');
  }

${lex.machineCode}

  const next = nextToken;

/* ---- productions ---- */
${parserOut.code}

  /* ---- drivers ---- */

  function parseAll() {
    depth = 0;
    nextToken();
    p_${g.headers.start}();
    if (tk !== T_EOF) perrAlt([T_EOF]);
  }

  /**
   * Push-mode statement loop. Parses statements until the buffer is
   * exhausted; an INCOMPLETE suspension rolls the current statement back
   * (fresh counter, label bindings, buffered quads) and reports the carry
   * point. Memory held across chunks is O(current statement), never the
   * whole document.
   */
  function parseChunk() {
    depth = 0;
    let stmtStart = 0;
    let cpFresh = freshCtr;
    try {
      nextToken();
      for (;;) {
        if (tk === T_EOF) return -1;
        stmtStart = ts;
        cpFresh = freshCtr;
        trail.length = 0;
        stmtBuf.length = 0;
        p_${stmtProd}();
        for (let i = 0; i < stmtBuf.length; i++) onQuad(stmtBuf[i]);
        stmtBuf.length = 0;
      }
    } catch (e) {
      if (e !== INCOMPLETE) throw e;
      freshCtr = cpFresh;
      for (let i = 0; i < trail.length; i++) env_labels.delete(trail[i]);
      trail.length = 0;
      stmtBuf.length = 0;
      return stmtStart;
    }
  }

  return {
    setInput(s, isFinal) { inp = s; len = s.length; pos = 0; final = isFinal ? 1 : 0; },
    enablePush() { trail = []; sink = (q) => { stmtBuf.push(q); }; },
    parseAll,
    parseChunk,
    result() {
      const prefixes = {};
      for (const [k, v] of env_prefixes) prefixes[k] = v;
      return { prefixes, base: env_base, version: env_version };
    },
  };
}

/* ================================================================
 * Public API
 * ================================================================ */

/**
 * One-shot parse of a complete document string.
 * options: { onQuad(quad), baseIRI }
 * returns: { prefixes, base, version }
 */
export function parse(input, options = {}) {
  const onQuad = options.onQuad || (() => {});
  const P = makeParser(options, onQuad);
  P.setInput(String(input), true);
  P.parseAll();
  return P.result();
}

/** Convenience: parse to an array of quads. */
export function parseToQuads(input, options = {}) {
  const quads = [];
  const res = parse(input, { ...options, onQuad: (q) => quads.push(q) });
  return { quads, ...res };
}

/**
 * Chunked push parser with bounded memory: only the current (incomplete)
 * statement is retained between push() calls.
 */
export function createPushParser(options = {}) {
  const onQuad = options.onQuad || (() => {});
  const P = makeParser(options, onQuad);
  P.enablePush();
  let carry = '';
  let ended = false;
  return {
    push(chunk) {
      if (ended) throw new Error('push after end');
      const s = carry.length > 0 ? carry + chunk : String(chunk);
      P.setInput(s, false);
      const idx = P.parseChunk();
      carry = idx < 0 ? '' : (idx > 0 ? s.slice(idx) : s);
    },
    end() {
      ended = true;
      P.setInput(carry, true);
      carry = '';
      const idx = P.parseChunk();
      if (idx >= 0) throw new ShuttleSyntaxError('unexpected end of input', 0, 0, 'EOF');
      return P.result();
    },
    get pending() { return carry.length; },
  };
}

/** Parse an (async) iterable of chunks (e.g. a Node fs ReadStream). */
export async function parseStream(iterable, options = {}) {
  const p = createPushParser(options);
  for await (const chunk of iterable) p.push(typeof chunk === 'string' ? chunk : chunk.toString('utf8'));
  return p.end();
}

export { NamedNode, BlankNode, Literal, Quad, DefaultGraph, DEFAULT_GRAPH, factory, ShuttleSyntaxError };

${ser.code}
`;

  return { code, grammar: g };
}
