/**
 * gen.test.js — node-only checks on the emitted Rust artifact (the full
 * cross-backend conformance identity run, which additionally needs cargo,
 * is test/conformance.sh).
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateModule } from '../src/generate.js';
import { syntheticGrammar } from './synthetic-fixture.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GRAMMAR = path.join(HERE, '..', '..', '..', 'grammars', 'turtle12.shuttle');

const { code, grammar } = generateModule(fs.readFileSync(GRAMMAR, 'utf8'), GRAMMAR);

test('generates a turtle12 module', () => {
  assert.equal(grammar.name, 'turtle12');
  assert.ok(code.length > 50_000);
});

test('artifact is dependency-free (std-only imports)', () => {
  const uses = [...code.matchAll(/^use ([a-z_]+)::/gm)].map((m) => m[1]);
  assert.ok(uses.length > 0);
  for (const u of uses) assert.equal(u, 'std', `non-std import: ${u}`);
  assert.ok(!/extern crate/.test(code));
});

test('artifact contains no unsafe code', () => {
  // the only permitted occurrence is the doc-comment mention of forbid()
  const nonDoc = code.split('\n').filter((l) => !l.trimStart().startsWith('//'));
  assert.ok(!nonDoc.some((l) => l.includes('unsafe')), 'unsafe outside comments');
});

test('public API surface is present', () => {
  for (const item of ['pub fn parse<', 'pub fn parse_to_triples', 'pub struct PushParser',
    'pub struct Writer', 'pub fn write_triples', 'pub enum Term', 'pub struct Triple',
    'pub struct SyntaxError', 'pub struct ParseOutcome']) {
    assert.ok(code.includes(item), `missing: ${item}`);
  }
});

test('checked-in generated artifact is current', () => {
  const checked = fs.readFileSync(path.join(HERE, '..', 'generated', 'turtle12.rs'), 'utf8');
  assert.equal(checked, code, 'generated/turtle12.rs is stale — run npm run generate');
});


/* ---- sq-uyney: >128-token-kind FIRST-mask array fallback ---- */



test('>128 token kinds fall back to a [u64; W] FIRST-mask array with the right bits', () => {
  const src = syntheticGrammar(140);
  const { code: syn } = generateModule(src, 'synthetic140.shuttle');
  // 140 keywords + IRIREF + '.' + EOF etc. > 128 kinds -> array masks
  const m = syn.match(/const (FS_\d+): \[u64; (\d+)\] = \[([^\]]+)\];/);
  assert.ok(m, 'expected a [u64; W] FIRST-mask array in the artifact');
  const words = Number(m[2]);
  const vals = m[3].split(',').map((s) => BigInt(s.trim()));
  assert.equal(vals.length, words);
  // recover the set bits and cross-check against the token-kind constants
  const bits = new Set();
  vals.forEach((w, wi) => {
    for (let b = 0n; b < 64n; b++) if ((w >> b) & 1n) bits.add(wi * 64 + Number(b));
  });
  // every kw token kind must be in the mask (the star-group FIRST set)
  const kindOf = new Map();
  for (const km of syn.matchAll(/const T_([A-Za-z0-9_]+): u16 = (\d+);/g)) kindOf.set(km[1], Number(km[2]));
  let kwKinds = 0;
  for (const [name, num] of kindOf) {
    if (/^LIT_/.test(name) || /^kw/.test(name)) continue; // literal-token naming varies; count via bits below
    void name; void num;
  }
  // the FIRST set of the star group is exactly the 140 keyword tokens:
  // every set bit must map to a token whose matcher is a fixed 'kwNNN' text.
  assert.equal(bits.size, 140, `expected 140 bits set, got ${bits.size}`);
  kwKinds = bits.size;
  assert.ok(kwKinds > 128, 'fixture must actually exceed the u128 width');
  // and the indexing expression is emitted
  assert.ok(syn.includes('>> 6) as usize] >> (self.tk & 63)) & 1 != 0'), 'array-mask test expression missing');
  // the artifact must still be std-only / unsafe-free
  assert.ok(!/\bunsafe\b/.test(syn.split('\n').filter((l) => !l.trimStart().startsWith('//')).join('\n')));
});

/* ---- sq-uyney: grammar-driven @maxdepth (per-production recursion cap) ---- */

test('@maxdepth(N) drives the generated depth guard in both backends', async () => {
  const src = syntheticGrammar(140);
  const { code: rs } = generateModule(src, 'synthetic140.shuttle');
  assert.ok(/fn p_nest\(/.test(rs), 'nest production generated');
  assert.ok(rs.includes('if self.depth > 7 { return Err(self.perr("MAXDEPTH")); }'),
    'Rust guard uses the @maxdepth(7) cap, not the 8192 default');
  // un-annotated recursive productions keep the 8192 default (the checked-in
  // turtle12 artifact, generated by the same backend, still carries it)
  assert.ok(code.includes('8192'), 'default cap preserved for un-annotated grammars');

  // behavioral boundary via the JS backend (same front end, same semantics)
  const { generateModule: genJs } = await import('../../gen-js/src/generate.js');
  const { code: js } = genJs(src, 'synthetic140.shuttle');
  assert.ok(js.includes('++depth > 7)'), 'JS guard uses the @maxdepth(7) cap');
  const tmp = path.join(HERE, '.synthetic140.tmp.mjs');
  fs.writeFileSync(tmp, js);
  try {
    const m = await import(tmp);
    const nest = (n) => `nest ${'['.repeat(n)}<http://e/x>${']'.repeat(n)} .`;
    m.parseToQuads(nest(6)); // within the cap
    assert.throws(() => m.parseToQuads(nest(7)), /MAXDEPTH|parse error/, 'cap enforced at the boundary');
  } finally {
    fs.unlinkSync(tmp);
  }
});
